cuda_compiler_version:
- None
#- 9.2
#- 10.0
- 10.1
- 11.0
- 11.1
cudnn:
- undefined
#- 7
#- 7
- 7
- 8
- 8
cdt_name:
- cos7
#- cos7
#- cos7
- cos7
- cos7
- cos7
docker_image:
- quay.io/condaforge/linux-anvil-comp7
#- quay.io/condaforge/linux-anvil-cuda:9.2 
#- quay.io/condaforge/linux-anvil-cuda:10.0 
- quay.io/condaforge/linux-anvil-cuda:10.1 
- quay.io/condaforge/linux-anvil-cuda:11.0 
- quay.io/condaforge/linux-anvil-cuda:11.1 
zip_keys:
  - - cudnn
    - cuda_compiler_version
    - docker_image
    - cdt_name
c_compiler_version:
- 8
cxx_compiler_version:
- 8

float_prec:
- low
- high
channel_sources:
- deepmodeling/label/dev,deepmodeling,defaults,nvidia
channel_targets:
- deepmodeling dev
python:
- 3.6
- 3.7
- 3.8
- 3.9
