cuda_compiler_version:
- None
- 9.2
- 10.0
- 10.1
cudnn:
- undefined
- 7
- 7
- 7
cdt_name:
- cos6
- cos6
- cos6
- cos6
docker_image:
- quay.io/condaforge/linux-anvil-comp7
- quay.io/condaforge/linux-anvil-cuda:9.2 
- quay.io/condaforge/linux-anvil-cuda:10.0 
- quay.io/condaforge/linux-anvil-cuda:10.1 
zip_keys:
  - - cudnn
    - cuda_compiler_version
    - docker_image
    - cdt_name
c_compiler_version:
- 7
cxx_compiler_version:
- 7

float_prec:
- low
- high
channel_sources:
- deepmodeling,defaults
channel_targets:
- deepmodeling main
python:
- 3.6
- 3.7
- 3.8
